import test, { after } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";
import { JSDOM } from "jsdom";
const require = createRequire(import.meta.url);
const { build } = createRequire(require.resolve("vite/package.json"))("esbuild");
const dir = path.resolve("node_modules/.tmp-library-navigation");
fs.mkdirSync(dir, {recursive:true});
await build({entryPoints:["src/components/BottomNav.tsx"], outfile:path.join(dir,"nav.mjs"), bundle:true, format:"esm", platform:"browser", external:["react","react/jsx-runtime"], logLevel:"silent"});
const dom = new JSDOM('<div id="root"></div>', {url:"https://example.test",pretendToBeVisual:true});
for (const key of ["window","document","HTMLElement","Element","Node","Event","CustomEvent","getComputedStyle","requestAnimationFrame","cancelAnimationFrame"]) globalThis[key] = dom.window[key];
Object.defineProperty(globalThis,"navigator",{value:dom.window.navigator,configurable:true});
globalThis.IS_REACT_ACT_ENVIRONMENT = true;
const React = await import("react");
const { createRoot } = await import("react-dom/client");
const { default: BottomNav } = await import(path.join(dir,"nav.mjs"));
const root = createRoot(document.getElementById("root"));
after(() => { React.act(() => root.unmount()); dom.window.close(); fs.rmSync(dir,{recursive:true,force:true}); });
test("existing shared dock exposes Library, preserves routes and marks active destination", () => {
  const changes=[];
  React.act(() => root.render(React.createElement(BottomNav,{active:"study-library",onChange:tab=>changes.push(tab)})));
  const buttons = [...document.querySelectorAll("nav button")];
  assert.equal(buttons.length,7);
  const library = buttons.find(b=>b.getAttribute("aria-label")==="My Study Library");
  assert.ok(library);
  assert.equal(library.getAttribute("aria-current"),"page");
  React.act(() => library.click());
  assert.equal(window.location.hash,"#/study-library");
  React.act(() => buttons.find(b=>b.getAttribute("aria-label")==="FlowPath").click());
  assert.equal(window.location.hash,"#/flowpath");
  React.act(() => buttons.find(b=>b.getAttribute("aria-label")==="Home").click());
  assert.deepEqual(changes,["home"]);
  assert.equal(document.querySelectorAll("[data-glass-dock]").length,1,"no duplicate navigation system");
});
