import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";

const subscription = fs.readFileSync("src/subscription/components/SubscriptionPage.tsx", "utf8");
const quote = fs.readFileSync("utils/serverQuotes.js", "utf8");
const entitlements = fs.readFileSync("api/_lib/entitlements.ts", "utf8");
const pdp = fs.readFileSync("src/PdpApp.tsx", "utf8");
const builder = fs.readFileSync("src/components/pdp/PdpPurchaseBuilder.tsx", "utf8");
const checkout = fs.readFileSync("src/components/checkout/CheckoutReviewStep.tsx", "utf8");
const root = fs.readFileSync("src/main.tsx", "utf8");
const notifications = fs.readFileSync("utils/siteNotifications.ts", "utf8");
const admin = fs.readFileSync("src/components/admin/products/ProductEditor.tsx", "utf8");

test("My Day feature is selected by default and changes subscription total", () => {
  assert.match(subscription, /current\.length === 0 \? \["my-day"\]/);
  assert.match(subscription, /selectedPlanPricePaise \+ featuresTotalPaise \+ productsTotalPaise/);
});

test("subscription quote preserves feature/product line kinds and IDs for unlocking", () => {
  assert.match(quote, /kind: item\.kind \|\| kind/);
  assert.match(quote, /featureId: item\.featureId \|\| null/);
  assert.match(quote, /subscriptionPlanId: line\.subscriptionPlanId \|\| null/);
  assert.match(entitlements, /includedProductIds: Array\.from\(new Set/);
  assert.match(entitlements, /selectedFeatureIds: uniqueFeatures/);
});

test("owned product PDP surfaces a prominent paid upgrade", () => {
  assert.match(pdp, /Course upgrade available/);
  assert.match(pdp, /New modules or files were added after your original purchase/);
  assert.match(pdp, /Buy upgrade/);
  // When the base course is owned the module picker is hidden; the upgrade is
  // bought directly from the prominent upgrade card.
  assert.match(builder, /isProductOwned && availableModes\.includes\("paid_update"\)/);
});

test("upgrade checkout lists exactly what is being added", () => {
  assert.match(quote, /detailItems/);
  assert.match(checkout, /New content included/);
  assert.match(checkout, /Your existing course stays owned/);
  assert.match(checkout, /Included add-ons & products/);
});

test("catalog changes notify purchased products from the server, not the client", () => {
  // The client-side baseline diff is gone (it re-announced "Product
  // unlocked" on every app open). Course-content notifications are now
  // generated by the server push system only.
  assert.doesNotMatch(root, /buildContentNotificationInventory/);
  assert.doesNotMatch(root, /createContentNotifications/);
  const cron = fs.readFileSync("api/cron/subscription-renewals.ts", "utf8");
  const send = fs.readFileSync("api/push/send.ts", "utf8");
  assert.match(cron, /Your course has new content/);
  assert.match(send, /Your course has new content/);
  // String and numeric product IDs both reach buyers (legacy array stores either).
  assert.match(cron, /Number\.isFinite\(Number\(update\.id\)\) \? Number\(update\.id\) : update\.id/);
});

test("admin enforces paid-update packaging for paid modules", () => {
  // Both guards are intact; the noun changed from "file" to "resource"
  // to match the rest of the editor's vocabulary, which is what broke
  // the old literal match.
  assert.match(admin, /must include at least one module or (resource|file)/);
  assert.match(admin, /must be included in a Paid update package/);
  // The empty-package guard only applies to an ACTIVE update — a
  // drafted one is allowed to be empty while it is being built.
  assert.match(admin, /u\.active && validIncludedIds\.length === 0/);
});
