import { FilePlus2, FolderPlus, Trash2 } from "lucide-react";
import type { CourseFile, CourseFileType, CourseModule } from "../types/course";

const FILE_TYPES: Array<{ value: CourseFileType; label: string }> = [
  { value: "youtube", label: "YouTube" }, { value: "video", label: "Video URL" }, { value: "audio", label: "Audio URL" },
  { value: "image", label: "Image / Cloudinary" }, { value: "pdf", label: "PDF" }, { value: "doc", label: "Google Doc / document" },
  { value: "sheet", label: "Google Sheet" }, { value: "google_form", label: "Google Form" }, { value: "mindmap", label: "Whimsical mind map" },
  { value: "embed", label: "GitHub Page / iframe embed" }, { value: "ebook", label: "E-book URL" },
];
const id = () => crypto.randomUUID();
const newModule = (): CourseModule => ({ id: id(), title: "New module", files: [], modules: [] });
const newFile = (): CourseFile => ({ id: id(), name: "New URL resource", type: "pdf", url: "", accessLevel: "included" });

export default function CourseUrlBuilder({ modules, onChange }: { modules: CourseModule[]; onChange: (modules: CourseModule[]) => void }) {
  return <section className="mt-6 rounded-2xl border border-violet-200 bg-violet-50/50 p-4 sm:p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-violet-600">URL-only course content</p><h3 className="mt-1 text-lg font-black">Modules & embedded resources</h3><p className="mt-1 text-xs leading-5 text-slate-500">No file upload or in-built document data is stored. Use public HTTPS embed URLs only.</p></div><button type="button" onClick={() => onChange([...modules, newModule()])} className="flex shrink-0 items-center gap-1.5 rounded-xl bg-violet-600 px-3 py-2 text-xs font-black text-white"><FolderPlus size={15} /> Module</button></div><div className="mt-4 space-y-3">{modules.length ? modules.map((module, index) => <ModuleEditor key={module.id} module={module} index={index} onUpdate={(next) => onChange(modules.map((item) => item.id === module.id ? next : item))} onDelete={() => onChange(modules.filter((item) => item.id !== module.id))} />) : <p className="rounded-xl border border-dashed border-violet-200 p-6 text-center text-xs font-semibold text-slate-400">No modules yet. Add a module, then paste URL resources.</p>}</div></section>;
}

function ModuleEditor({ module, index, onUpdate, onDelete, depth = 0 }: { module: CourseModule; index: number; onUpdate: (module: CourseModule) => void; onDelete: () => void; depth?: number }) {
  return <div className={`rounded-2xl border bg-white p-4 ${depth ? "border-slate-200" : "border-violet-100 shadow-sm"}`}><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg bg-violet-100 text-xs font-black text-violet-700">{index + 1}</span><input value={module.title} onChange={(event) => onUpdate({ ...module, title: event.target.value })} className="min-w-0 flex-1 rounded-lg border border-slate-200 px-3 py-2 text-sm font-black outline-none focus:border-violet-400" /><button type="button" onClick={() => onUpdate({ ...module, files: [...module.files, newFile()] })} className="grid h-9 w-9 place-items-center rounded-lg bg-emerald-50 text-emerald-700" aria-label="Add URL resource"><FilePlus2 size={16} /></button><button type="button" onClick={() => onUpdate({ ...module, modules: [...module.modules, newModule()] })} className="grid h-9 w-9 place-items-center rounded-lg bg-violet-50 text-violet-700" aria-label="Add nested module"><FolderPlus size={16} /></button><button type="button" onClick={onDelete} className="grid h-9 w-9 place-items-center rounded-lg bg-rose-50 text-rose-600" aria-label="Delete module"><Trash2 size={15} /></button></div><div className="mt-3 space-y-2">{module.files.map((file) => <FileEditor key={file.id} file={file} onUpdate={(next) => onUpdate({ ...module, files: module.files.map((item) => item.id === file.id ? next : item) })} onDelete={() => onUpdate({ ...module, files: module.files.filter((item) => item.id !== file.id) })} />)}</div>{module.modules.length > 0 && <div className="mt-3 space-y-3 border-l-2 border-violet-100 pl-3">{module.modules.map((child, childIndex) => <ModuleEditor key={child.id} module={child} index={childIndex} depth={depth + 1} onUpdate={(next) => onUpdate({ ...module, modules: module.modules.map((item) => item.id === child.id ? next : item) })} onDelete={() => onUpdate({ ...module, modules: module.modules.filter((item) => item.id !== child.id) })} />)}</div>}</div>;
}

function FileEditor({ file, onUpdate, onDelete }: { file: CourseFile; onUpdate: (file: CourseFile) => void; onDelete: () => void }) {
  return <div className="rounded-xl bg-slate-50 p-3"><div className="grid gap-2 sm:grid-cols-[150px_1fr_auto]"><select value={file.type} onChange={(event) => { const type = event.target.value as CourseFileType; onUpdate({ ...file, type, provider: type === "mindmap" ? "whimsical_mindmap" : type === "embed" ? "external_embed" : file.provider }); }} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-bold">{FILE_TYPES.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select><input value={file.name} onChange={(event) => onUpdate({ ...file, name: event.target.value })} placeholder="Resource name" className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-bold outline-none" /><button type="button" onClick={onDelete} className="grid h-9 w-9 place-items-center rounded-lg bg-rose-50 text-rose-600"><Trash2 size={14} /></button></div><input type="url" value={file.url || ""} onChange={(event) => onUpdate({ ...file, url: event.target.value, embedUrl: event.target.value })} placeholder={file.type === "mindmap" ? "https://whimsical.com/your-public-mind-map-ID" : file.type === "embed" ? "https://username.github.io/repository/" : "https://public-or-embedded-url"} className="mt-2 w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-xs outline-none focus:border-violet-400" />{file.type === "mindmap" && <p className="mt-2 text-[10px] font-semibold text-violet-600">Whimsical → Share → Enable Public Access → Copy link. The app converts it to whimsical.com/embed/:id.</p>}</div>;
}
