/** Responsive tiers derived from the *container* width (never the device width). */
export type Tier = "xxs" | "xs" | "sm" | "md" | "lg" | "xl";

export type AttachmentKind = "upload" | "screenshot";

export interface Attachment {
  id: string;
  kind: AttachmentKind;
  name: string;
  src: string;
  w?: number;
  h?: number;
  size?: number; // bytes (approx for data URLs)
}

export type StepStatus = "pending" | "active" | "done";

export interface ThinkingStep {
  label: string;
  detail?: string;
  status: StepStatus;
}

export type MsgStatus = "thinking" | "streaming" | "complete" | "error";

/**
 * The structure Lumen chooses for an answer, based on what was asked.
 * Surfaced to the user as a small chip so the adaptation is legible.
 */
export type ResponseFormat =
  | "concise"
  | "steps"
  | "comparison"
  | "deep-dive"
  | "code"
  | "timeline"
  | "visual"
  | "practice"
  | "feedback";

/** An image produced by the assistant's image generator. */
export interface GeneratedImage {
  prompt: string;
  src: string;
  alt: string;
  caption: string;
  /** CSS aspect-ratio, e.g. "3 / 2" — reserves space so nothing reflows on load. */
  aspect: string;
  status: "rendering" | "done";
}

/** Classification of *why* an answer was wrong — drives targeted repair. */
export type MistakeKind =
  | "conceptual"
  | "formula"
  | "calculation"
  | "sign"
  | "reading"
  | "logic"
  | "unit"
  | "misinterpretation"
  | "recall"
  | "incomplete"
  | "careless";

/** Diagnosis attached to a distractor: picking it reveals a specific mistake. */
export interface OptionDiagnosis {
  kind: MistakeKind;
  note: string;
}

/** An interactive multiple-choice question rendered inside an assistant message. */
export interface QuizQuestion {
  q: string;
  options: string[];
  correct: number; // index into options
  explain: string; // step-by-step explanation used for grading
  difficulty: 1 | 2 | 3; // 1 foundation · 2 core · 3 stretch
  concept: string; // stable concept id, links to the student model
  /** One entry per option; null on the correct answer. */
  optionNotes?: (OptionDiagnosis | null)[];
}

/** State of an interactive practice set. Answers live here so they persist. */
export interface InteractiveQuiz {
  topic: string;
  questions: QuizQuestion[];
  answers: (number | null)[];
  submitted: boolean;
  /** Calibrated starting difficulty of this set (adaptive practice). */
  level?: 1 | 2 | 3;
}

export interface Message {
  id: string;
  role: "user" | "assistant";
  content: string;
  attachments?: Attachment[];
  createdAt: number;
  status: MsgStatus;
  errorMessage?: string;
  errorRetryable?: boolean;
  errorKind?: string;
  thinking?: ThinkingStep[];
  thinkingOpen?: boolean;
  thinkingMs?: number;
  modelLabel?: string;
  /** Interactive practice set attached to an assistant message. */
  quiz?: InteractiveQuiz;
  /** On a user answer-sheet message: id of the assistant message holding the quiz. */
  quizRef?: string;
  /** Structure chosen for this answer — drives the format chip. */
  format?: ResponseFormat;
  /** Contextual next-step chips rendered under the response. */
  followUps?: string[];
  /** Image generated by the assistant for this response. */
  image?: GeneratedImage;
}

export interface Chat {
  id: string;
  title: string;
  course: string;
  courseShort: string;
  pinned?: boolean;
  modelId: string;
  messages: Message[];
}

export interface AIModel {
  id: string;
  name: string;
  short: string;
  desc: string;
  badge?: string;
}
